input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      "app" => "demo_app"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
